### ISSUE TITLE
不支持swoole4吗？

### ISSUE THREAD

**Issue by zhong0060** [lanlin/abstract-swoole#1]
Problem 1
    - Installation request for lanlin/codeigniter-swoole ^2.0 -> satisfiable by lanlin/codeigniter-swoole[2.0.0].
    - lanlin/codeigniter-swoole 2.0.0 requires ext-swoole ^2.0.0 -> the requested PHP extension swoole has the wrong version (4.1.2) installed.

**Comment by lanlin** [comment]
已经修正。
