### ISSUE TITLE
一直报这样的错误

### ISSUE THREAD

**Issue by zhong0060** [lanlin/abstract-swoole#2]
Fatal error: Assignments can only happen to writable values in /home/web/btc/application/config/timers.php on line 16

A PHP Error was encountered

Severity:    Compile Error
Message:     Assignments can only happen to writable values
Filename:    /home/web/btc/application/config/timers.php
Line Number: 16

Backtrace:

PHP Fatal error:  Uncaught Swoole\ExitException: swoole exit. in /home/web/btc/system/core/Common.php:631
Stack trace:
#0 /home/web/btc/system/core/Common.php(689): _error_handler(64, 'Assignments can...', '/home/web/btc/a...', 16)
#1 [internal function]: _shutdown_handler()
#2 {main}
  thrown in /home/web/btc/system/core/Common.php on line 631

Fatal error: Uncaught Swoole\ExitException: swoole exit. in /home/web/btc/system/core/Common.php:631
Stack trace:
#0 /home/web/btc/system/core/Common.php(689): _error_handler(64, 'Assignments can...', '/home/web/btc/a...', 16)
#1 [internal function]: _shutdown_handler()
#2 {main}
  thrown in /home/web/btc/system/core/Common.php on line 631
[2018-09-21 21:02:30 *30405.3]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Swoole\ExitException: swoole exit. in /home/web/btc/system/core/Common.php:631
Stack trace:
#0 /home/web/btc/system/core/Common.php(689): _error_handler(64, 'Assignments can...', '/home/web/btc/a...', 16)
#1 [internal function]: _shutdown_handler()
#2 {main}
  thrown in /home/web/btc/system/core/Common.php on line 631.

**Comment by lanlin** [comment]
@zhong0060 尝试一下最新的版本 v2.0.2

**Comment by zhong0060** [comment]
@lanlin 
还是报错的，环境是php7.1.2，CI版本是3.1.9，swoole是4.2.1

> [2018-09-25 21:49:53 $28572.0]	WARNING	swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0
> [2018-09-25 21:49:53 $29779.0]	TRACE	swReactorEpoll_add(:140): add event[reactor_id=0, fd=15, events=512]
> [2018-09-25 21:49:53 *29779.3]	TRACE	Context(:32): alloc stack: size=2097152, ptr=0x7fd10494b010.
> [2018-09-25 21:49:53 *29779.3]	TRACE	sw_coro_func(:232): Create coro id: 1, coro total count: 1, heap size: 943552
> PHP Fatal error:  Assignments can only happen to writable values in /home/web/btc/application/config/timers.php on line 16
> PHP Fatal error:  Uncaught Swoole\ExitException: swoole exit. in /home/web/btc/system/core/Common.php:631
> Stack trace:
> #0 /home/web/btc/system/core/Common.php(689): _error_handler(64, 'Assignments can...', '/home/web/btc/a...', 16)
> #1 [internal function]: _shutdown_handler()
> #2 {main}
>   thrown in /home/web/btc/system/core/Common.php on line 631
> [2018-09-25 21:49:53 *29779.3]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Swoole\ExitException: swoole exit. in /home/web/btc/system/core/Common.php:631
> Stack trace:
> #0 /home/web/btc/system/core/Common.php(689): _error_handler(64, 'Assignments can...', '/home/web/btc/a...', 16)
> #1 [internal function]: _shutdown_handler()
> #2 {main}
>   thrown in /home/web/btc/system/core/Common.php on line 631.

**Comment by lanlin** [comment]
@zhong0060
抱歉，我这边无法重现你这个错误。请升级到 v2.0.3.
你仔细核对下 /home/web/btc/application/config/timers.php 中的代码，或者贴出来看看呢。

**Comment by zhong0060** [comment]
@lanlin 
已经是升级到最新的2.0.3了，代码都是包里面提供的test示例

timers.php
`<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Swoole Timers Config
|--------------------------------------------------------------------------
|
| Demo:
|    $timers['route/for/timer']       = 10000;    // micro seconds
|    $timers['tests/test/task_timer'] = 10000;    // micro seconds
|
|    This means countroller method under 'route/for/timer' will be
|    execute every per 10s.
|
*/
$timers = ['testsw/task_timer']=10000;


// the end
return $timers;`
Testsw.php
`<?php
/**
 * Created by Zzz.
 * Date: 2018/9/21
 * Time: 下午9:09
 */
class Testsw extends CI_Controller{

    public function task()
    {
        $data = $this->input->post();
        log_message('error', var_export($data, true));
    }

    public function task_timer(){
        log_message('error', 'timer works!');
    }
    public function send()
    {
        try
        {
            \CiSwoole\Core\Client::send(
                [
                    'route'  => 'testsw/task',
                    'params' => ['hope' => 'it works!'],
                ]);
        }
        catch (\Exception $e)
        {
            log_message('error', $e->getMessage());
            log_message('error', $e->getTraceAsString());
        }
    }
}`

**Comment by lanlin** [comment]
@zhong0060 呃，亲。你这个属于语法错误。
![image](https://user-images.githubusercontent.com/3468024/46066233-c80fa300-c1a6-11e8-8256-f1c62ffd7926.png)

![image](https://user-images.githubusercontent.com/3468024/46066180-a6162080-c1a6-11e8-97d2-a0f14229c6f0.png)

```php
// 你的代码
$timers = ['testsw/task_timer']=10000;

// 我的代码
$timers['tests/test/task_timer'] = 10000;
```

`['testsw/task_timer'] ` 定义了一个数组的值，它本身并不是个变量。
`['testsw/task_timer']=10000; ` 你不能把一个值赋给另一个值。

**Comment by zhong0060** [comment]
@lanlin 谢谢了！浪费你时间了
